server:
  port: 5000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   # 自己就是注册中心，所以自己不注册自己
    fetch-registry: false         # 自己就是注册中心，所以不需要“从注册中心取回信息”
    service-url:                  # 客户端访问Eureka 时使用的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
